os:
    - linux
    - osx

language:
    - python

before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi

install:
    - sudo ./run.sh install

script:
    - sudo ./run.sh check
    - sudo ./run.sh deploy
