os:
    - linux
    - osx

language:
    - python

before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi

install:
    - sudo pip install -r requirements.txt
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y shellcheck; else brew install shellcheck; fi

script:
    - ./ansible_check.sh
    - sudo ./ansible_install.sh
