language: generic

before_install:
  - sudo apt-get -qq update && sudo apt-get install python python-pip

install:
  - sudo pip install pipenv
  - pushd ansible && pipenv install && popd

script:
  - make -C ansible/roles/common test
