language: generic

before_install:
  - sudo apt-get -qq update && sudo apt-get install -yqq python python-pip

install:
  - sudo pip install pipenv

script:
  - cd ansible
  - make install
  - pipenv run pip list
  - make -C roles/common test
