---
# Variables for common role

common_packages:
    - vim
    - tmux
    - zsh
    - stow
    - wget
    - entr
    - silversearcher-ag
    - the_silver_searcher

common_configs:
    - vim
    - tmux
    - zsh
    - virtualenvs
