---
- name: light - stat
  stat:
    path: /usr/bin/light
  register: p

- name: light - git clone
  git:
    repo: https://github.com/haikarainen/light.git
    dest: "{{ download_dir }}/light"
    version: 1.1.2
  when: p.stat.exists == false

- name: light - make
  make:
    chdir: "{{ download_dir }}/light"
  when: p.stat.exists == false

- name: light - make install
  make:
    chdir: "{{ download_dir }}/light"
    target: install
  when: p.stat.exists == false

- name: light - clean up
  file:
    path: "{{ download_dir }}/light"
    state: absent
  when: p.stat.exists == false
