---
# This role contains common plays

- name: install common packages
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ common_packages }}"

- name: chsh zsh
  shell: "chsh -s $(which zsh) {{ lookup('env', 'SUDO_USER') }}"

- name: stow configs
  shell: pushd .. && stow "{{ item }}" && popd
  with_items: "{{ common_configs }}"

- name: install oh_my_zsh
  shell: 'sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"'
  become: true
  become_user: "{{ lookup('env', 'SUDO_USER') }}"

- name: pip install requirements
  shell: pip install -r ../requirements.txt
