---
# This role contains common plays

# For macOS, we cannot run brew as root
- name: install common macOS packages
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ common_packages }}"
  become: true
  become_user: "{{ lookup('env', 'SUDO_USER') }}"
  when: ansible_os_family == 'DARWIN'

- name: install common linux packages
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ common_packages }}"
  when: ansible_os_family != 'DARWIN'

- name: chsh zsh
  shell: "chsh -s $(which zsh) {{ lookup('env', 'SUDO_USER') }}"

- name: stow configs
  shell: pushd .. && stow "{{ item }}" && popd
  with_items: "{{ common_configs }}"
  become: true
  become_user: "{{ lookup('env', 'SUDO_USER') }}"

- name: install oh_my_zsh
  shell: "source ../install-oh-my-zsh.sh"
  become: true
  become_user: "{{ lookup('env', 'SUDO_USER') }}"

- name: pip install requirements
  shell: pip install -r ../requirements.txt
