---
- name: update repositories and cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: install packages
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ apt_packages }}"

- name: mkdir {{ download_dir }}
  file:
    path: "{{ download_dir }}"
    state: directory
    mode: 0755

- name: install spotify
  include_tasks: spotify.yml

- name: install light
  include_tasks: light.yml

- name: install signal-desktop
  include_tasks: signal-desktop.yml

- name: install zoom
  include_tasks: zoom.yml

- name: install openconnect
  include_tasks: openconnect.yml

- name: install pyenv
  include_tasks: pyenv.yml
