---
- name: openconnect - stat
  stat:
    path: /usr/local/sbin/openconnect
  register: p

- name: openconnect - git clone
  git:
    repo: https://github.com/dlenski/openconnect.git
    dest: "{{ download_dir }}/openconnect"
    version: globalprotect
  when: p.stat.exists == false

- name: openconnect - install dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ openconnect_dependencies }}"
  when: p.stat.exists == false

- name: openconnect - autogen.sh
  command: ./autogen.sh
  args:
    chdir: "{{ download_dir }}/openconnect"
  when: p.stat.exists == false

- name: openconnect - configure
  command: ./configure
  args:
    chdir: "{{ download_dir }}/openconnect"
  when: p.stat.exists == false

- name: openconnect - make
  make:
    chdir: "{{ download_dir }}/openconnect"
  when: p.stat.exists == false

- name: openconnect - make install
  make:
    chdir: "{{ download_dir }}/openconnect"
    target: install
  when: p.stat.exists == false

- name: openconnect - ldconfig
  command: ldconfig
  when: p.stat.exists == false

- name: openconnect - clean up
  file:
    path: "{{ download_dir }}/openconnect"
    state: absent
  when: p.stat.exists == false
