template: sustained_memory_pressure
      on: system.memory_full_pressure
   class: Latency
    type: System
component: Memory
  lookup: average -1m unaligned of full 60
   units: %
   every: 10s
    warn: $this > 1
   delay: down 2m
 summary: Sustained memory pressure
    info: All non-idle tasks stalled on memory for more than 1 percent of the interval
      to: silent
