[db]
    db = dbengine
    update every = 1s
    storage tiers = 3
    dbengine tier 0 retention size = 4GiB
    dbengine tier 0 retention time = 1d
    dbengine tier 1 retention size = 4GiB
    dbengine tier 1 retention time = 7d
    dbengine tier 2 retention size = 2GiB
    dbengine tier 2 retention time = 30d
[web]
    bind to = 127.0.0.1:19999 192.168.121.1:19999
    allow connections from = localhost 127.0.0.1 192.168.121.*
    allow dashboard from = localhost 127.0.0.1
    allow badges from = localhost 127.0.0.1
    allow management from = localhost 127.0.0.1
    allow netdata.conf from = localhost 127.0.0.1
    allow streaming from = 192.168.121.*
[registry]
    allow from = localhost 127.0.0.1
[health]
    enabled = yes
    script to execute on alarm = /bin/true
[plugins]
    ebpf = yes
    debugfs = yes
