# git — native home-manager module; all git config lives in the `settings`
# attrset below (replaced the old packages/git/.gitconfig). The gh credential
# helper entries are generated by programs.gh.gitCredentialHelper (gh.nix).
{ ... }:
{
  # delta is its own module in home-manager 26.05. enableGitIntegration wires
  # core.pager and interactive.diffFilter into git.
  programs.delta = {
    enable = true;
    enableGitIntegration = true;
    options = {
      navigate = true;
      line-numbers = true;

      # Light-mode feature, activated by `DELTA_FEATURES=+theme-light` which the
      # `light`/`dark` switcher exports (see packages/zsh/.zsh/theme.zsh). delta
      # only bundles standard syntax themes, so dark mode keeps delta's default
      # dark theme rather than the custom "Catppuccin Mocha" bat theme.
      theme-light = {
        light = true;
        syntax-theme = "GitHub";
      };
    };
  };

  programs.git = {
    enable = true;
    lfs.enable = true;

    # Raw git config (the `settings` attrset mirrors git config sections).
    settings = {
      user = {
        name = "Victor Yap";
        email = "vicyap@users.noreply.github.com";
      };

      init.defaultBranch = "main";
      core = {
        editor = "vim";
        autocrlf = "input";
      };
      pull.ff = "only";
      push = {
        default = "current";
        autoSetupRemote = true;
      };
      color.ui = "auto";

      alias.initer =
        "!f() { git init && git commit --allow-empty --allow-empty-message --message ''; }; f";

      # Normalize the live ghostty theme line back to the committed default.
      filter.ghostty-theme = {
        clean = "sed 's/^theme = .*/theme = Catppuccin Mocha/'";
        smudge = "cat";
      };
    };
  };
}
